#!/bin/bash
gmcs `pkg-config --libs gtk-sharp-2.0 glade-sharp-2.0 gnome-sharp-2.0 gconf-sharp-2.0` -resource:gui.glade -r:/usr/lib/mono/2.0/Mono.Posix.dll -r:ICSharpCode.SharpZipLib -r:System.Windows.Forms.dll -recurse:./src/*.cs -out:GnomeArtNg.exe

